# Generated by Django 3.0.5 on 2020-05-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message_status', '__first__'),
        ('order', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectUser', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('message_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_status.MessageStatus')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
