# Generated by Django 3.0.5 on 2020-05-26 19:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('order_status', '__first__'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('items_ordered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=5)),
                ('amount_due', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_outsanding', models.IntegerField()),
                ('date_and_time_of_order', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_status.OrderStatus')),
                ('venddor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
        ),
    ]
