# Generated by Django 3.0.5 on 2020-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='venddor_id',
            new_name='vendor_id',
        ),
    ]
